create table cliente (id_cliente bigint not null, primer_apellido varchar(255), primer_nombre varchar(255), segundo_apellido varchar(255), segundo_nombre varchar(255), primary key (id_cliente));
create table tarjeta (numero bigint not null, activa boolean, bloqueada boolean, fecha_vencimiento date, saldo numeric(38,2), unicamente_dolar boolean, id_cliente bigint, primary key (numero));
create table tipo_producto (id_tipo_producto bigint not null, nombre_producto varchar(255), numero_producto bigint, primary key (id_tipo_producto));
create table tipo_transaccion (id_tipo_transaccion bigint not null, tipo varchar(255), primary key (id_tipo_transaccion));
create table transaccion (id_transaccion bigint not null, fecha_transaccion timestamp(6), habilitada boolean, valor numeric(38,2), id_tarjeta bigint, id_tipo_transaccion bigint, primary key (id_transaccion));
create sequence cliente_seq start with 1 increment by 50;
create sequence tarjeta_seq start with 1 increment by 50;
create sequence tipo_producto_seq start with 1 increment by 50;
create sequence tipo_transaccion_seq start with 1 increment by 50;
create sequence transaccion_seq start with 1 increment by 50;
alter table if exists tarjeta add constraint FKntkbeiatvm2e4h6mnxeebkbcc foreign key (id_cliente) references cliente;
alter table if exists transaccion add constraint FKrx8l643bd6qb8vtxw3jc2if7q foreign key (id_tarjeta) references tarjeta;
alter table if exists transaccion add constraint FK2itf9bvwycr3foe4f2jxnwpqe foreign key (id_tipo_transaccion) references tipo_transaccion;
INSERT INTO cliente(id_cliente,primer_nombre,segundo_nombre,primer_apellido,segundo_apellido) values(1, 'Pedro', 'Jose', 'Rodriguez', 'Munuera');
INSERT INTO cliente(id_cliente,primer_nombre,segundo_nombre,primer_apellido,segundo_apellido) values(2, 'Danny', 'Sebastian', 'Cardenas', 'Ruiz');
INSERT INTO cliente(id_cliente,primer_nombre,segundo_nombre,primer_apellido,segundo_apellido) values(3, 'Laura', 'Milena', 'Martinez', 'Toro');
INSERT INTO cliente(id_cliente,primer_nombre,segundo_nombre,primer_apellido,segundo_apellido) values(4, 'Maria', '', 'Ruiz', 'Benitez');
INSERT INTO tipo_producto(id_tipo_producto, numero_producto, nombre_producto) VALUES (1, 123456, 'AHORROS');
INSERT INTO tipo_producto(id_tipo_producto, numero_producto, nombre_producto) VALUES (2, 654321, 'CORRIENTE');
INSERT INTO tarjeta(numero,id_cliente,fecha_vencimiento,activa,saldo,bloqueada,unicamente_dolar) Values (1234563634538520, 1, '2025-03-31', 1, 1000.00,0,0); 
INSERT INTO tarjeta(numero,id_cliente,fecha_vencimiento,activa,saldo,bloqueada,unicamente_dolar) Values (6543213498065610, 1, '2025-03-31', 0, 1000.00,0,0); 
INSERT INTO tarjeta(numero,id_cliente,fecha_vencimiento,activa,saldo,bloqueada,unicamente_dolar) Values (1234568358308160, 2, '2025-03-31', 0, 1000.00,0,0); 
INSERT INTO tarjeta(numero,id_cliente,fecha_vencimiento,activa,saldo,bloqueada,unicamente_dolar) Values (6543212143086740, 2, '2025-03-31', 1, 1000.00,0,0); 
INSERT INTO tarjeta(numero,id_cliente,fecha_vencimiento,activa,saldo,bloqueada,unicamente_dolar) Values (1234568340960060, 3, '2025-03-31', 1, 1000.00,0,0); 
INSERT INTO tarjeta(numero,id_cliente,fecha_vencimiento,activa,saldo,bloqueada,unicamente_dolar) Values (6543215010822670, 3, '2025-03-31', 0, 1000.00,0,0); 
INSERT INTO tarjeta(numero,id_cliente,fecha_vencimiento,activa,saldo,bloqueada,unicamente_dolar) Values (1234569047941090, 4, '2025-03-31', 0, 1000.00,0,0); 
INSERT INTO tarjeta(numero,id_cliente,fecha_vencimiento,activa,saldo,bloqueada,unicamente_dolar) Values (6543218125947740, 4, '2025-03-31', 1, 1000.00,0,0);
INSERT INTO tipo_transaccion(id_tipo_transaccion, tipo) VALUES (1, 'RECARGAR');
INSERT INTO tipo_transaccion(id_tipo_transaccion, tipo) VALUES (2, 'COMPRA');
